### ISSUE TITLE
python caesar.py problem 

### ISSUE THREAD

**Issue by malabdaly** [0blio/Caesar#14]
How i can install Missing dependencies.
Some dependencies are missing, do you want to install them? (y/n): y
[!] Missing dependencies.

**Comment by 0blio** [comment]
The agent generator require two libraries in order to run.
The libraries are **requests** and **grequests**.

The script try to install those libraries by using **pip**, but probably it is not installed on your system.
To install **pip** type:
`sudo apt install python-pip`

Then re-run the script and input **y**, it should fix the problem.
Let me know.

**Comment by opti7** [comment]
I'm having the same issue. I'm running ParrotOS and I have both python2.7 and 3.7 installed, as well as pip. I tried running `sudo apt install python-pip` which it returned that it's already installed. I also tried running the problem using `python caesar.py` and `python2.7 caesar.py`. Neither of them worked.

**Comment by 0blio** [comment]
Nice, issue solved.
